@startuml
set separator none
title User

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("BoardApplication.BoardApplication_boundary", "BoardApplication", $tags="") {
  Component(BoardApplication.BoardApplication.User, "User", $techn="Module", $descr="", $tags="", $link="")
  Component(BoardApplication.BoardApplication.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
}

Rel(BoardApplication.BoardApplication.User, BoardApplication.BoardApplication.Common, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml