@startuml
set separator none
title Like

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("BoardApplication.BoardApplication_boundary", "BoardApplication", $tags="") {
  Component(BoardApplication.BoardApplication.Article, "Article", $techn="Module", $descr="", $tags="", $link="")
  Component(BoardApplication.BoardApplication.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
  Component(BoardApplication.BoardApplication.Like, "Like", $techn="Module", $descr="", $tags="", $link="")
}

Rel(BoardApplication.BoardApplication.Article, BoardApplication.BoardApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(BoardApplication.BoardApplication.Article, BoardApplication.BoardApplication.Like, "uses", $techn="", $tags="", $link="")
Rel(BoardApplication.BoardApplication.Like, BoardApplication.BoardApplication.Common, "listens to", $techn="", $tags="", $link="")
Rel(BoardApplication.BoardApplication.Like, BoardApplication.BoardApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(BoardApplication.BoardApplication.Like, BoardApplication.BoardApplication.Article, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml