services:
  mysql:
    image: 'mysql:8.0'
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_volume:/var/lib/mysql

  redis:
    image: 'redis:8.0'
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/data
      - ./redis.conf:/etc/redis/redis.conf

volumes:
  mysql_volume:
  redis_volume: