spring:
  application:
    name: board
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only