spring:
  application:
    name: board
  profiles:
    active: local

  jpa:
    open-in-view: false

  modulith:
    events:
      republish-outstanding-events-on-restart: true

  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

server:
  tomcat:
    mbeanregistry:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_only

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: redis
      port: 6379
      username: ""
      password: ""

logging:
  level:
    sql: error

jwt:
  secret: jwt_secret